title: 롤하는 개발자의 개발 알림장
email: kho0307@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  언젠가 취미로 개발하는 날을 꿈구며 얕은 지식을 깊게 하려고
  블로그를 시작합니다.
github_username: brawman
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Braw!!! Man!!!"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "언젠가 취미로 개발하는 날을 꿈구며 얕은 지식을 깊게 하려고 블로그를 시작합니다."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://brawman.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brawman"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:kho0307@gmail.com

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brawman"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
